### ISSUE TITLE
Add custom error types instead of using `String` as the error type

### ISSUE THREAD

**Issue by i509VCB** [staktrace/cafebabe#2]
It would be useful to have dedicated error types for the parsing process. For use a more explicit error would be useful. You could also implement the `Error` trait on the error type so you can still rely on the resulting error type being `Display`.

**Comment by staktrace** [comment]
Yeah, that's fair. I got a bit lazy with that when I wrote the code since I didn't need strong error typing. Will one error type suffice for you, or would it be useful to have different error types for different kinds of errors? Maybe an enumeration error type? Let me know.

I also need to audit the way I glue together the error strings, I think I changed my approach partway through so some of the error strings might not make sense.

**Comment by staktrace** [comment]
FYI I'm actively working on fixing this.

**Comment by staktrace** [comment]
I pushed commits to main that add a ParseError type

**Comment by staktrace** [comment]
This is all done now.
