### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by i509VCB** [staktrace/cafebabe#3]
I think it would be useful to have a testing suite built-in that could be run against on CI (GitHub actions) to verify class files are parsed properly.

I would be willing to implement some of the testing, but a few questions about what you would prefer:

- Build tooling - do we scale up to something on the level of Gradle or just use a bunch of Makefiles or bash scripts to compile our test files.
- Compilers - Do we want to also test other compilers such as ECJ in our tooling? May not get to ECJ immediately but javac will be on the roster first.
- Test artifacts - Specifically regarding code style as to prevent conflict hell with git. Ideally something that we could just run an autoformatter on.
- Oddball artifacts - It may be useful to craft some very specific testing artifacts that javac or any compiler couldn't generate but are still considered legal bytecode - ASM may be useful for generating these special oddballs.

**Comment by staktrace** [comment]
- I would prefer bash scripts/Makefiles because I really don't like gradle
- I would like to see test files structured so that there are different source dirs for different languages (e.g. java/kotlin/groovy/etc) and converters that generate class files from them. They can use one compiler or multiple different compilers. And alongside those source dirs would be a "class" source dir that has class files with a "no-op" compiler. That will allow us to hand-craft class files (using whatever tools you prefer) and check them in. If you want to write some asm to generate oddball class files you could do that as another "language" that runs on .asm files or whatever.
- I'm not sure what you mean by your third bullet point, can you clarify? Are you talking about formatting of the source code? Or of the testing source files?

**Comment by i509VCB** [comment]
FYI I was refering to this when mentioning asm https://gitlab.ow2.org/asm/asm

It's essentially just a bytecode library.

**Comment by staktrace** [comment]
If you haven't started working on this yet, I'll probably pick it up in the next day or two.

**Comment by i509VCB** [comment]
Sure you can take this up, been busy with other things recently
