### ISSUE TITLE
Add a method for accessing the constant pool by index

### ISSUE THREAD

**Issue by zigazeljko** [staktrace/cafebabe#4]
The code inside `CodeData` references constants by their `u16` indices, but this library does not expose any way to access these constants by index.

My idea is to add a method like `pub fn get(&self, index: u16) -> Option<ConstantPoolItem<'a>>` that uses the same logic as `ConstantPoolIter::next`, but for the item at `self.constant_pool[index].`

**Comment by staktrace** [comment]
I've been meaning to work on exposing the code data in a better way. The library could implement bytecode parsing and return opcodes with their associated data (including constant pool references) as first class data structures.

I'd be interested in hearing more about your use case for the library to design the API accordingly.

The API you suggested is slightly more complicated than it might first seem because some entries in the constant pool (long/double values) take up two indices and you'd have to account for that. Not hard, but it would be a linear iteration rather than constant time.

**Comment by staktrace** [comment]
@accusitive can you provide more details on your use case and what you're trying to do? It would help inform the API design.

**Comment by accusitive** [comment]
I've been trying it out, and its great, No complaints from me.
