### ISSUE TITLE
Make ClassFile ownable(?)

### ISSUE THREAD

**Issue by accusitive** [staktrace/cafebabe#9]
I'll admit, I'm kind of a rookie when it comes to rust lifetimes. I can normally get by with little to no friction, but this issue has completely stumped me.

It seems that the issue is that the data for each ClassFile must live as long or longer than the ClassFile itself, Which makes it impossible(?) to use a function to populate a struct field with ClassFiles.

I'm more than willing to fix this myself if I have a few pointers on how, since i've just been fumbling around the codebase changing things from &'a [u8] to Vec<u8> with no success. Thank you so much for this great crate :)

**Comment by staktrace** [comment]
Yeah this is the key downside of my choice of implementation. It requires that you have to hold the data for the `ClassFile` in a lifetime that's longer than the `ClassFile` itself. It's not entirely impossible to populate a struct field with `ClassFile`, it just requires that the struct you're populating itself must be outlived by the `Vec<u8>` that holds the data for the `ClassFile`.

Having `cafebabe::ClassFile` have an `into_owned()` kind of function is possible, but it would require creating duplicates of all the public structures (including `ClassFile` itself) such that they have owned types and no lifetime parameters. e.g. all the `Cow<'a, str>` would be `String` in the "owned" variant of the structs. I'm not super motivated to implement that since it's a bunch of code duplication.

**Comment by deeprobin** [comment]
@accusitive Can you publish a crate of your forked version? I'm interested in this owned version to implement a VM.
